"""Remove SevDesk and FinTS tables

Revision ID: 1e3f16c582f3
Revises: 5750435ca4eb
Create Date: 2026-04-13 20:10:14.570635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3f16c582f3'
down_revision: Union[str, None] = '5750435ca4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
