// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn2pTrwrJjoTcXxjbtz0HaiPE5bCwsOOw',
    appId: '1:1036924064365:web:7c008479cf2617d192e564',
    messagingSenderId: '1036924064365',
    projectId: 'workmate-private-55afd',
    authDomain: 'workmate-private-55afd.firebaseapp.com',
    storageBucket: 'workmate-private-55afd.firebasestorage.app',
    measurementId: 'G-0WSYZPZ03J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7srWTH7Kvo91ibC2nmgTXgaTw3-sU4Dw',
    appId: '1:1036924064365:android:af5cafe1afd36a5f92e564',
    messagingSenderId: '1036924064365',
    projectId: 'workmate-private-55afd',
    storageBucket: 'workmate-private-55afd.firebasestorage.app',
  );
}
